CC=cc

all: example

example: bison-example.tab.o lex.yy.o!

$(CC) -o example bison-example.tab.o lex.yy.o!



bison-example.tab.o: example.h bison-example.y

bison -d bison-example.y

$(CC) -c bison-example.tab.c



lex.yy.o: tree.h bison.tab.h test.l

flex test.l

$(CC) -c lex.yy.c


clean:

-rm *.o bison-example.tab.c bison-example.tab.h example